title: Muhammet Öztürk
description: Cyber Security Blog
author: Muhammet Öztürk
logo: /static/img/ozturk.jpg
github: https://github.com/ozmu
about: Cyber Security Engineer Candidate

baseurl: "//ozmu.github.io/"
url: "//ozmu.github.io/"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \ozturkmuhammeet
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
